### PR TITLE
Tests for CreateUser

### PR DESCRIPTION
**Pull request by GustavoMeza**
image

Further things to consider:
- What does the function should do if the id is already in the UserSet?
  - Override the user information (Currently does)
  - Throw an error (Currently tests)
  - Return an ErrorT (Probably the best solution, but requires some design discussion)
- Am I missing any other requirement?
- Do you think I should abstract the mocking process, e.g. move `const username='my_username'` outside the test? (This will help with DRY)

### CODE REVIEW

**Comment by beris147** [comment]
The id is assigned by socket.io, it uses the socket.id to communicate directly with the node. https://stackoverflow.com/a/20973977 
So, if we assume that the id is unique we shouldn't have to worry about it... 
The only situation that I can think of when we have a repeated ID is where the `disconnect` method fails, if that happens I think is safe to override the user info. 

However, if an user disconnects by mistake we don't have anything to reconnect.

**Review by beris147 — APPROVED** [review]
Looks good to me, but I think we can have all the variables as global, and just clean the userSet on the method `afterEach()`. But it's up to you.

**Comment by beris147** [comment]
Also, do not forget to link the pull requests to some issue to see some progress!

**Comment by GustavoMeza** [comment]
solves #27

**Comment by GustavoMeza** [comment]
image

**Pull request merged**
