### PR TITLE
Create test.yml

### PR DESCRIPTION
**Pull request by beris147**
Continuation for #62 
This should run on every pull request, checking all the tests (frontend and backend). Does this seem right @danielmnv?

### CODE REVIEW

**Review by GustavoMeza — APPROVED** [review]
Looks like it runs the server tests both in ```npm ci``` and ```npm test```.

Otherwise, looks good

**Comment by beris147** [comment]
> Looks like it runs the server tests both in `npm ci` and `npm test`.
> 
> Otherwise, looks good

Fixed

**Comment by danielmnv** [comment]
It's okay but the workflows will run on every push of all branches. The correct behavior should be only on pull requests, isn't it? @beris147

**Comment by beris147** [comment]
> It's okay but the workflows will run on every push of all branches. The correct behavior should be only on pull requests, isn't it? @beris147 

Alright, I'll fix it in a moment

**Pull request merged**
